name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: |
          npm version prepatch --preid=alpha --git-tag-version false
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add package.json
          git commit -m "Increment version number"
          git tag -a "v$(npm pkg get version)" -m "Release $(npm pkg get version)"
          git push --tags
          git push origin main
      - name: Create Release
        uses: actions/create-release@v1
        with:
          release_name: "Release $(npm pkg get version)"
          draft: false
          prerelease: true
          auto_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TITLE: "Release $(npm pkg get version)"
          RELEASE_NOTES: "Release notes for $(npm pkg get version)"
          RELEASE_TAG: "v$(npm pkg get version)"
          RELEASE_DRAFT: false
          RELEASE_PRERELEASE: true
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
